packages:
  - 'packages/*'
  - 'templates/*'
  - 'docs/*'
ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
onlyBuiltDependencies:
  - better-sqlite3
catalog:
  '@biomejs/biome': ^1.9.4
  typescript: ^5.7.3
